version: "3"
services:
    php_apache:
        image: sabyrzhan/paxful-test-solution
        build:
            context: .
        volumes:
            - "./:/var/www/html"
        ports:
            - "80:80"
