version: "3"
services:
  php_apache:
    image: sabyrzhan/paxful-test-solution
    environment:
      APP_KEY: base64:nFRTmt4q+VWNtKGawRMwVLMcuxa6L868QEziZCIbXF0=
      MAIL_MAILER: smtp
      MAIL_HOST: 192.168.1.161
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: hello@example.com
      MAIL_FROM_NAME: "WebApp"
      DB_CONNECTION: pgsql
      DB_HOST: 192.168.1.161
      DB_PORT: 5432
      DB_DATABASE: paxful-test-db
      DB_USERNAME: postgres
      DB_PASSWORD: test
      BLOCKED_IP_EMAIL: test@domain.com
    ports:
      - "80:80"
