apiVersion: v1
kind: Service
metadata:
  name: paxful-test-solution-service
  labels:
    app: webapp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: webapp

---
apiVersion: v1
kind: Service
metadata:
  name: paxful-email-service
  labels:
    app: webapp
spec:
  type: ClusterIP
  ports:
    - port: 8025
      targetPort: 8025
      protocol: TCP
      name: http
  selector:
    app: webapp
