apiVersion: v1
kind: Service
metadata:
  name: paxful-test-solution-service
  labels:
    app: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: webapp
